# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-DHstEdPYaVstuyJHPwXqKV3oFFabg49
"""

from google.colab import files
files.upload()

# Commented out IPython magic to ensure Python compatibility.
!unzip MarchMadnessApproaches-complete.zip
# %cd MarchMadnessApproaches-complete
!pip install torch transformers datasets scikit-learn pandas -q

!python train_all_bert_variants.py --data-dir data
!python model_comparison.py --data-dir data

!ls -la models/
!ls *.csv

!ls -lh models/

# Commented out IPython magic to ensure Python compatibility.
!git config --global user.email "rushilkosaraju2@gmail.com"
!git config --global user.name "Rushil"

# %cd /content/MarchMadnessApproaches-complete

!git init
!git remote add origin https://github.com/terabytetyson/MarchMadnessApproaches.git
!git add iterations/v11_bert_* bert_trainer.py train_all_bert_variants.py model_comparison.py generate_submission.py
!git commit -m "Add BERT variants trained on Colab"
!git push https://rushilkosaraju2:Reddiah1@github.com/terabytetyson/MarchMadnessApproaches.git HEAD:main

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/MarchMadnessApproaches-complete

# Check what's actually there
!ls -la iterations/
!ls -la *.py | head

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!git config --global user.email "rushilkosaraju2@gmail.com"
!git config --global user.name "Rushil"

!git clone https://rushilkosaraju2:Reddiah1@github.com/terabytetyson/MarchMadnessApproaches.git repo
# %cd repo

# Check what's in the original iterations folder
!ls iterations/

# Add and push what we have
!git add .
!git commit -m "Add BERT training code from Colab"
!git push origin main

!tar -czf models_and_code.tar.gz models/ iterations/v11_bert_* *.py